### ISSUE TITLE
aggregations of question tasks should include all p values for possible answers

### ISSUE THREAD

**Issue by vrooje** [zooniverse/aggregation#100]
Currently the aggregations appear to only report p(most_likely_label). That will be very useful for some researchers, but _only_ reporting that complicates some analyses. If I'm looking to weight an external quantity by p(specific_label), I can't directly use p(most_likely_label) because it will switch meanings from subject to subject. And if the most likely label's p-value is the only thing reported even when the question task has >2 possible answers, I can't recover the information I need at all.

So the aggregations should report p(most likely) and p(specific labels) for all possible labels, even when there are only 2 possible labels.

**Comment by ggdhines-zz** [comment]
I had talked to people about what sorts of results they wanted - there is always a trade about being ease of understanding and detail. The aggregation results are not really intended for people to then go and do additional things like weighting. My understanding was that we assumed (I think not without reason) that people who wanted to do advanced analysis would work directly from the raw classifications. @aliburchard thoughts?

**Comment by vrooje** [comment]
Is it particularly hard to report this or something?

**Comment by ggdhines-zz** [comment]
not hard to report - but I want the csv files to be as easy to read as possible

**Comment by vrooje** [comment]
I agree, but I don't agree that the way to do it is to refuse to provide full classification information, when that's what we've promised people.

If people want to aggregate the classifications themselves they can always do that, but right now I am forced to do so for GZ Bar Lengths because 2 of my question tasks have 3 possible answers and all I get is 1 number for each task. If I wanted to know what the p value was for a non-dominant answer for 1 subject, I would have to re-reduce all of the data.

**Comment by ggdhines-zz** [comment]
?? I'm missing something here - "refuse to provide full classification information" We are providing full classification information - the project builder provides full classification dumps which give you everything you need. The aggregation is by definition a summary.

**Comment by vrooje** [comment]
The goal of the aggregation is to enable research teams to use citizen science data without having to develop their own data reduction for relatively standard use cases. 

Using individual p values for subjects across the whole range of possible values is a standard use case in many fields. We need to do that.

The p(most-likely-answer) is useful too, but providing _only_ that removes too much information. If you provide p values for each label the researcher can easily reconstruct p(most-likely-answer), but the reverse is not true for any question task with more than 3 possible answers.

Additionally, a file with the columns
`subject_id most_likely_label p_most_likely_label num_users p_labelA p_labelB p_labelC`
is _not_ significantly more confusing than a file without the 3 (or however many) p_label# columns. If the end user can cope with the complexity of having a separate file for each task aggregation, there's no reason to believe they can't handle a few extra columns in an already-small file.

The aggregation part of the new Zooniverse is, to me, one of the most important value-added parts that will facilitate more science results. It's far more than just a summary. This is a small change to the implementation that will add huge value.

**Comment by aliburchard** [comment]
Yup, we definitely need more information to make full use of the aggregated data. What Brooke suggested, a file with: 

subject_id most_likely_label p_most_likely_label num_users p_labelA p_labelB p_labelC

would be ideal. And, in fact, for questions in which users can select multiple answers, that's critical and we are (or should be) already providing aggregated data in the format.

Suggesting that project owners hit up the raw classification data if they want to do _very basic_ aggregations isn't a good solution, because the current JSON-embedded structure isn't accessible to the vast majority of non-astrophysicist researchers. Yes, researchers can learn to use it, but it often requires using a new computer language to do so and is a huge barrier to entry. So, in general, but especially until the raw classification dumps are more accessible, providing more robust aggregations so the researchers can really sink their teeth into is really critical for zooniverse project builders who want to really explore their data.

**Comment by ggdhines-zz** [comment]
I wasn't suggesting that researchers should rely on the raw classifications for basic aggregations - I think my disagreement was about whether or not what @vrooje  wants to do counts as "basic". I don't think it does - but that is kinda irrelevant if both @aliburchard  and Brooke want this info in the results. @aliburchard - the results for when users are allowed multiple answers should already be in this format. (If not, I will definitely fix that.)

**Comment by chrislintott** [comment]
I agree that @vrooje’s suggestion is useful, and I think this extra information would be useful in a large number of cases, and should be the default.

**Comment by ggdhines-zz** [comment]
I'm going to close this issue for now - I've sent @vrooje an updated format. I've basically set things so that every question gets both a detail output and a summary output which has the information @vrooje wants. If that format is still missing something, I'll reopen this.

**Comment by vrooje** [comment]
Haven't really dug into the numbers yet so I can't speak to that, but the format is great -- thanks.
