### ISSUE TITLE
Getting duplicates that are not flagged as such

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/aggregation#106]
Myself and some people who have been helping me classify have occasionally noticed that we're getting repeat images which do NOT have the red flag in the upper left corner denoting them as such. As best I can tell, I do not have duplicate images in the directory from which I uploaded my subject set.

**Comment by ggdhines-zz** [comment]
Unless I'm really misunderstanding something, this isn't an aggregation issue. Duplicate subjects is an ongoing issue - see zooniverse/Panoptes#1069. Feel free to reopen if this is something specifically to do with aggregation.
