### ISSUE TITLE
Unnecessary nested folders in Aggregate Export from PFE

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/aggregation#145]
Right now, the results within the export archive contain a folder called `tmp` and a folder within that called `988` (or whatever your project ID is). Within that, we have something like `512_Main_Workflow`. 
It makes sense that there would be one folder per workflow, so that third one is fine - but the tmp and project ID folders are unnecessary and shouldn't be created.

**Comment by ggdhines-zz** [comment]
The tmp folder is definitely not useful and I'll upload code to fix in that in a second. I disagree about the project id folder being unnecessary so I'm going to leave that in.

**Comment by alexbfree** [comment]
OK. Just curious on your reasoning... given there is no way to generate an export for more than one project at a time, why is it useful? isn't the project id and/or name adequately conveyed by the tar file name?

**Comment by ggdhines-zz** [comment]
I want to make sure that when people unzip things everything stays together. If you unzip the file in a directory with lots of other files (probably your Downloads directory), it help you keep track of things.

**Comment by alexbfree** [comment]
Most unzip programs will default to unzipping into a named directory under the current folder, following the name of the zip/tar. so you then end up with two nested directories.
I guess this may vary between Linux/OSX/Windows and depends what unzip method you use. Personally i don't think it's our job to anticipate people's unzip strategy. Naming the archive according to what it is should be sufficient.

If we really must keep this, we should at least include the project name as well as / instead of the ID. ID alone is not human-useful.

**Comment by ggdhines-zz** [comment]
I agree with including the project name - see #147

**Comment by alexbfree** [comment]
Perfect - thanks!

**Comment by vrooje** [comment]
No, tar -xzvf does not default to creating a new directory -- as an
example. I don't think we should rely on an external protocol to keep files
from overwriting or mixing contents from multiple projects in the same
directory; but I agree with removing ./tmp !

Another option would be to put the project_id and workflow_id in each of
the filenames. Then it wouldn't matter what the directory structure was, or
even if 2 projects had identical workflow content.
