### ISSUE TITLE
impossible answers

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#149]
For @mkosmala 's project Season Spotter Image Marking, I'm getting what appears to be an impossible answer to a follow up question. For subject id 572490 and user_id 1386240, I'm getting a follow up question answer of 4 (for the marking task colorsandcones) (4 is in the index of the answer in a list of possible answers, I think the list has something to do with colour, the possible answers are red, orange, yellow and brown). That list is 0-indexed so 4 should be an impossible value. The workflow version associated with that annotation is 41.22 which is the current one. I know Margaret has been doing some work on running the aggregation code herself so hopefully she can confirm that this is happening (based on csv classifications). If confirmed I don't know how often this happens and technically it would be a bug with PFE but given that the bug seems to happen at random, I think tracking it down might be impossible. So in the mean time, any such results will be ignored. So this issue is kind of a bug report and also letting people like @camallen @astopy  and @marten know about the issue

**Comment by mkosmala** [comment]
I think the 4 is valid. There are multiple point tools for the task colorsandcones. For this classification, the user made one point -- and used the "Flowers" tool. The allowed values are, in fact, colors. But there are 6 options (white, pink, red, orange, yellow, purple). There is another point tool for the same task called "Leaves that are NOT green" that has the 4 options you list (red, orange, yellow, brown). 

So maybe there's a bug in matching up tools to answers?

JSON for this classification:
`[{"task":"badimage","value":"Yes","task_label":"Do you have a clear view of an outdoor landscape?"},
{"task":"weather","value":"Overexposed white sky, but not foggy, raining, or snowing","task_label":"What is the weather?"},
{"task":"T8","value":[{"tool":0,"frame":0,"closed":true,"points":[{"x":112.74414388667125,"y":677.7513364958883},{"x":9.674126686177251,"y":851.3482622531708},{"x":326.1171619508518,"y":851.3482622531708}],"details":[],"tool_label":"Trees with BROAD leaves"},{"tool":0,"frame":0,"closed":true,"points":[{"x":1049.4155282701079,"y":505.96271204857743},{"x":940.9207733222196,"y":634.3521050565677},{"x":1201.3081851971517,"y":659.6683233961713}],"details":[],"tool_label":"Trees with BROAD leaves"}],"task_label":"Draw a shape containing most of the leaves for a single tree. Do this for 3 trees. (You can do more trees if you want to.) If you can't identify individual trees, click Next. "},
{"task":"colorsandcones","value":[{"x":1058.4567578490987,"y":587.3362709973036,"tool":0,"frame":0,"details":[{"value":4}],"tool_label":"Flowers"}],"task_label":"For the trees you chose, put a mark in the middle of any that have flowers, cones, or non-green leaves. If none, click Next"},
{"task":"anomalies","value":["None of these"],"task_label":"Is there anything odd? (You can choose more than one.)"}]`
