### ISSUE TITLE
trying to create json schema for aggregation results

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#5]
I'm trying to create the schema but have hit the point where I don't understand what JSON is doing or trying to do. For example, consider the schema:

{
  "tool_classification": {
    "type": "array",
    "description": "which tool the cluster corresponds to, e.g. a point cluster corresponding to an adult penguin",
    "items": [
      {
        "type": "object",
        "description": "mapping from tool to percentage of markings/probability",
        "patternProperties": {
          "2": {
            "type": "number",
            "description": "percentage/probability"
          },
          "additionalProperties": false
        }
      },
      {
        "type": "number",
        "description": "total number of people with markings in this cluster"
      }
    ],
    "additionalProperties": false
  },
  "requiredProperties": [
    "tool_classification"
  ],
  "additionalProperties": false
}

As far as I can tell, this should require an object (dictionary) with the kw tool_classification and the value of a list (with a few required elements). But the json blob 

[
  {
    "3": "a" 
  }
]

apparently matches this schema (according to http://jsonschemalint.com/draft4/ and https://pypi.python.org/pypi/jsonschema) even though the two are nothing alike. Any ideas @marten @camallen @edpaget @alexbfree @astopy @eatyourgreens ?

**Comment by camallen** [comment]
@ggdhines I assume you are trying to use the defined json schema to try and validate the following json object?

``` JSON
[ { "3": "a"} ]
```

Any code examples that we can use to reproduce?

**Comment by ggdhines-zz** [comment]
The website  http://jsonschemalint.com/draft4/  allows you to give a schema and validate code.

**Comment by camallen** [comment]
Cool - i had a quick look and think there are some inconsistencies, like you require tools_classification as an array which is supplied. 

I'd start with the smallest working set to match your expected data and build it up, piece by piece.

**Comment by ggdhines-zz** [comment]
irrelevant now - no one uses the json results
