### ISSUE TITLE
KeyError: 'tools'

### ISSUE THREAD

**Issue by ggdhines-zz** [zooniverse/aggregation#61]
View details in Rollbar: [https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/49/](https://rollbar.com/Zooniverse/Zooniverse_Aggregation/items/49/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/engine/jobs.py", line 10, in aggregate
    with AggregationAPI(project_id, environment=environment) as project:
  File "/app/engine/aggregation_api.py", line 224, in __init__
    self.__setup__()
  File "/app/engine/aggregation_api.py", line 312, in __setup__
    self.workflows,self.versions,self.instructions,self.updated_at_timestamps = self.__get_workflow_details__()
  File "/app/engine/aggregation_api.py", line 888, in __get_workflow_details__
    for tool_index,tool in enumerate(task["tools"]):
KeyError: 'tools'
```

**Comment by ggdhines-zz** [comment]
this was caused by the retina project and a drawing task. An example drawing task from Whales as Individuals has the keys [u'tools', u'instruction', u'type', u'help', u'next']. I use tool to figure out what marking tools the user is using for the task. Note that for WasI, for this task we have type ="drawing". 
For Retina, I only have the keys [u'instruction', u'type', u'help', u'next'] with type = "crop". I don't know how much of Retina is based on Panoptes and how much is a custom build but for now I think this is more that the aggregation does support the custom tools in Retina rather than a bug that would affect other projects.
@camallen @aliburchard - can you tell more about the Retina tool. I have some vague memory of Ali saying that the retina team would take care of the aggregation themselves.

**Comment by camallen** [comment]
retina is a panoptes front end project using an experimental tool. best to ask @brian-c for details on how the tool works. We should support all the front end tools for aggregation even if projects use custom setups.

**Comment by brian-c** [comment]
Ah, sorry: A `crop` task produces an annotation with a `value` map of the `x`, `y`, `width`, and `height` of the area the user cropped from the natural width and height of the subject image.

After a crop task, the view of the subject is cropped to those bounds, but _maintaining the natural aspect ratio of the image_ (for now).

**Comment by ggdhines-zz** [comment]
Still not sure what I'm supposed to be doing with results from the crop tool - suspect that this will involve a talk with Ali and the Retina people. Will have to wait until I get back from vacation.

**Comment by aliburchard** [comment]
@ggdhines we'll want to incorporate the crop tool into aggregation for future projects that might use it. The retinas team turned out to not be doing the aggregation we anticipated (aggregating polygons, and _then_ calculating polygon ratio), so it might actually be a good test case to build the aggregation on. 

But yes, can and should wait until you get back from holiday.
