### ISSUE TITLE
Represent Drawing Tasks in a Single File

### ISSUE THREAD

**Issue by edpaget** [zooniverse/aggregation#73]
@aliburchard asked me to post this here. I think there's a simpler way to represent drawing tasks so they can all be exported as part of a single CSV. They just need a `type` column with the type of drawing task that's happening, and then a `markings` column with an array of (x,y) points to represent the drawing. Rotation, or other parameters are not necessary. This is what I'm doing for the Spark-based CSV exports in https://github.com/zooniverse/warehouse

**Comment by ggdhines-zz** [comment]
I had asked people if they wanted different types of markings to be given in one or multiple csv files - zooniverse/Panoptes-Front-End#525. The agreement was that multiple csv files made sense. Also had a talk with @marten and @aliburchard a while back and I don't think anyone really uses the representation that Ed is talking about.
